### PR TITLE
Fixes for commandline exporting of a single mesh or anim.

### PR DESCRIPTION
**Pull request by HarrievG**
- safe guard for area var, actually not used.
- is_export_go now supports 'mesh' which only returns the active object and 'meshes' which is original behaviour
- exportAnim and exportMesh can now be called safely from the python interactive console after selecting or activation the export targets.

### CODE REVIEW

**Comment by KozGit** [comment]
Hey, thanks for this!  Sorry I just noticed the pull request - I'll get it merged shortly.
Please let me know if there is anything else you think should/could be changed - this was thrown together pretty quickly to meet my specific use case ( batch importing and editing of stock meshes & anims from D3), so the workflow may not be ideal for other uses. ( edit: Especially the whole collections implementation )

**Comment by HarrievG** [comment]
MD5Camera ;) 

in all seriousness:
I am no specialist in python (tbh, i try to avoid it.) OR blender, so IMHO nothing has to go or has to be changed as long as it functions and i didnt break anything.  
After i got aquinted with blenderPY it was easy enough to add an use case .👍 

( About collections : Point is, collection and batch export will be managed by the export tags in the d3 def files themselves. My implemention of this resides in the [DHEWM3 ](github.com/dhewm/dhewm3) codebase and will possibly be added in the next major release, but because of the specificness to dhewm3 I would keep your setup as functional as possible so it does not become an exporter that ONLY works with dhewm3)

**Comment by HarrievG** [comment]
still active?

**Review by KozGit — APPROVED** [review]

**Comment by KozGit** [comment]
Hey, I can't believe I hadn't merged this yet - my apologies and thanks for the fixes!

**Comment by HarrievG** [comment]
no problem! thank you for setting this up in the first place.
I will let you know if i make any other additions or improvements :)

**Pull request merged**
